service: serverless-nodearch

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  bundle:
    linting: false
    excludeFiles: "**/*.test.ts"
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

functions:
  client:
    handler: dist/handlers/client-handler.handler
    events:
    - httpApi:
        path: '/client-management/{proxy+}'
        method: '*'
  user:
    handler: dist/handlers/user-handler.handler
    events:
    - httpApi:
        path: '/user-management/{proxy+}'
        method: '*'

package:
  exclude:
  - .git/**
  - src/**
  - test/**
  - e2e/**
  - nodemon.json
  - README.md

plugins:
  - serverless-offline


